### ISSUE TITLE
numpy 较高版本会导致代码运行错误

### ISSUE THREAD

**Issue by mfdycs** [jmhIcoding/flowcontainer#12]
代码环境：
- Python: `3.9.16`
- tshark: `TShark (Wireshark) 4.0.3 (v4.0.3-0-gc552f74cdc23)`
- numpy: `1.24.2`
- flowcontainer: `6.2`

报错信息如下：

```shell
Reading 1592993485_clear.pcap...
D:\ProgramData\Anaconda3\envs\1\lib\site-packages\flowcontainer\reader.py:113: UserWarning: Running Error : tshark parse error : 'setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (6007, 11) + inhomogeneous part.'.
  warnings.warn("Running Error : tshark parse error : '{0}'."
Traceback (most recent call last):
  File "D:\Code\1\demo.py", line 5, in <module>
    result = extract(r"1592993485_clear.pcap", filter='', extension=['tls.handshake.ciphersuite'])
  File "D:\ProgramData\Anaconda3\envs\1\lib\site-packages\flowcontainer\extractor.py", line 36, in extract
    result = flow_generator.combine(result,extension)
  File "D:\ProgramData\Anaconda3\envs\1\lib\site-packages\flowcontainer\flow_generator.py", line 29, in combine
    for packet in packets:
TypeError: 'NoneType' object is not iterable
```

**Comment by mfdycs** [comment]
尝试将 `numpy` 降级后代码正常运行，降级版本为 `numpy==1.19.5`

**Comment by sanqudui8ban** [comment]
同样的问题，怎么搞

**Comment by sanqudui8ban** [comment]
代码有问题，我把reader.py中第255行 从：
result = np.asarray(result)
改成：
result = np.asarray(result,  dtype=object)
就好了

**Comment by jmhIcoding** [comment]
把numpy降级即可。
