### ISSUE TITLE
解析一个pcap文件时报错

### ISSUE THREAD

**Issue by XueYanYu** [jmhIcoding/flowcontainer#5]
文件链接：https://mcfp.felk.cvut.cz/publicDatasets/IoT-23-Dataset/IndividualScenarios/CTU-IoT-Malware-Capture-1-1/
报错信息：
C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)
Traceback (most recent call last):
  File "C:\Users\username\Desktop\P2\tshark.py", line 12, in <module>
    GetSignalSample()
  File "C:\Users\username\Desktop\P2\tshark.py", line 4, in GetSignalSample
    result = extract(
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flowcontainer\extractor.py", line 36, in extract
    result = flow_generator.combine(result,extension)
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flowcontainer\flow_generator.py", line 32, in combine
    result[key] = result.get(key, Flow()).add(packet,extention)
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\flowcontainer\flows.py", line 113, in add
    raise ValueError("Packet {} incompatible with flow {}" .format(packet, self))
ValueError: Packet ['2018-05-09-192.168.100.103.pcap' 'udp' '11757' '1525891666.012055000'
 '40' '192.168.100.103' '22.224.141.116' '43763' '26597' '20' list([])] incompatible with flow [Time 02:47:45.011902 to 02:47:45.011902] 192.168.100.103:43763 <->   100.118.73.85:23129 [Payload Packet Size Length 1] [extension: {}]

**Comment by jmhIcoding** [comment]
这个网络流是长流，导致五元组信息错乱了。

**Comment by Alonepeople** [comment]
你好，我的出现这样问题（数据包2.12GB）：
Reading E:\RawMalware\Stratosphere_Malware\Sality_2017-11-23_win16.pcap...
Packet ['E:\\RawMalware\\Stratosphere_Malware\\Sality_2017-11-23_win16.pcap'
 ('udp', 'UDP') '117903' '344900.395332000' '49' '192.168.1.126'
 '114.39.114.214' '63057' '7291' '29' list(['', ''])] incompatible with flow [Time 02:52:15.883362 to 02:52:15.883362]   192.168.1.126:63057 <->  114.26.237.242:8095  [Payload Packet Size Length 1] [extension: {}]
Packet ['E:\\RawMalware\\Stratosphere_Malware\\Sality_2017-11-23_win16.pcap'
 ('udp', 'UDP') '117903' '365101.405826000' '63' '192.168.1.126'
 '188.25.135.69' '63057' '7215' '43' list(['', ''])] incompatible with flow [Time 02:52:15.883362 to 07:48:20.395332]   192.168.1.126:63057 <->  114.26.237.242:8095  [Payload Packet Size Length 2] [extension: {}]
Packet ['E:\\RawMalware\\Stratosphere_Malware\\Sality_2017-11-23_win16.pcap'
有很多如上的情况，但是最后可以处理得到流的个数，不会报错出现程序停止的情况！！不知道是什么原因，或者有什么办法可以去掉这个不匹配的消息提醒？同时我最新版本的flowcontainer==6.3确实会出现两个协议情况，导致流ID不是很理想！
