### ISSUE TITLE
解析包时Flow类的add方法出现IndexError: list index out of range异常

### ISSUE THREAD

**Issue by FantasticJiang** [jmhIcoding/flowcontainer#7]
报错内容如下：
> C:\Users\issuer> python.exe d:/Flowcontainer库学习/基本功能.py
> Reading ./TestPcaps/ios1_1-10000.pcapng...
> Traceback (most recent call last):
>   File "d:\Flowcontainer库学习\基本功能.py", line 21, in <module>
> &nbsp;&nbsp; &nbsp;&nbsp; result=extract(pcap,extension=extensions)
>   File "C:\Users\issuer\AppData\Local\Programs\Python\Python310\lib\site-packages\flowcontainer\extractor.py", line 36, in extract
> &nbsp;&nbsp;&nbsp;&nbsp;result = flow_generator.combine(result,extension)
>   File "C:\Users\issuer\AppData\Local\Programs\Python\Python310\lib\site-packages\flowcontainer\flow_generator.py", line 32, in combine
>  &nbsp;&nbsp;&nbsp;&nbsp;result[key] = result.get(key, Flow()).add(packet,extention)
>   File "C:\Users\issuer\AppData\Local\Programs\Python\Python310\lib\site-packages\flowcontainer\flows.py", line 126, in add
> &nbsp;&nbsp;&nbsp;&nbsp;if extension[i] not in self.extension:
> IndexError: list index out of range

代码非常简单，就引入extract函数，然后调用即可。
一开始以为是包过大，后来缩小到10M也会报错，根据报错找到Flow类add方法的对应代码：
```
for i in range(len(packet[-1])):  
    if packet[-1][i] != "":  
        if extension[i] not in self.extension:
            self.extension.setdefault(extension[i],[])  
        self.extension[extension[i]].append((packet[-1][i],len(self.ip_lengths)))  
```
看上去是extention的元素比packet的元素少，导致extension[i]超出范围。是什么原因导致两个变量长度不同呢？
当前暂时的解决办法是把for循环的range改成取packet和extension的最小值，避免超出范围，但可能会缺少部分解析结果。

[报错的报文和脚本.zip](https://github.com/jmhIcoding/flowcontainer/files/9314643/default.zip)

**Comment by jmhIcoding** [comment]
我运行了你的代码，可以正常解析数据，没有出现报错。你可以更新wireshark的版本。
我测试时的 wireshark版本号是Wireshark 3.4.8 (v3.4.8-0-g3e1ffae201b8)

以下是解析结果：
```bash
[
  {
    "flow_info": [
      "花椒直播ios1_1-10000.pcapng",
      "tcp",
      "0"
    ],
    "Src IP": "192.168.20.7",
    "Dst IP": "36.110.213.180",
    "Sport": 50101,
    "Dport": 80,
    "Source": [
      "192.168.20.7",
      50101
    ],
    "Destination": [
      "36.110.213.180",
      80
    ],
    "Time Start": 1658219896.625866,
    "Time End": 1658219896.666146,
    "Extensions": {
      "http.request.method": [
        [
          "GET",
          3
        ]
      ],
      "http.request.uri": [
        [
          "/huajiao_8.4.3.cfg",
          3
        ]
      ],
      "http.host": [
        [
          "sdk.live.360.cn",
          3
        ]
      ],
      "http.user_agent": [
        [
          "curl/7.29.0",
          3
        ]
      ],
      "http.request.line": [
        [
          "User-Agent: curl/7.29.0\\r\\n,Host: sdk.live.360.cn\\r\\n,Accept: */*\\r\\n",
          3
        ]
      ]
    }
  },
  {
    "flow_info": [
      "花椒直播ios1_1-10000.pcapng",
      "tcp",
      "1"
    ],
    "Src IP": "192.168.20.7",
    "Dst IP": "36.110.213.180",
    "Sport": 50103,
    "Dport": 80,
    "Source": [
      "192.168.20.7",
      50103
    ],
    "Destination": [
      "36.110.213.180",
      80
    ],
    "Time Start": 1658219896.623759,
    "Time End": 1658219896.664857,
    "Extensions": {
      "http.request.method": [
        [
          "GET",
          3
        ]
      ],
      "http.request.uri": [
        [
          "/codec?sdkver=1.7.0.5&bid=huajiao&pid=ios&mid=3BB057EF965F4AA2A92D7E15ADA04DA9&ver=8.4.3&model=iPhone",
          3
        ]
      ],
      "http.host": [
        [
          "sdk.live.360.cn",
          3
        ]
      ],
      "http.user_agent": [
        [
          "curl/7.29.0",
          3
        ]
      ],
      "http.request.line": [
        [
          "User-Agent: curl/7.29.0\\r\\n,Host: sdk.live.360.cn\\r\\n,Accept: */*\\r\\n",
          3
        ]
      ]
    }
  },
  {
    "flow_info": [
      "花椒直播ios1_1-10000.pcapng",
      "tcp",
      "2"
    ],
    "Src IP": "192.168.20.7",
    "Dst IP": "36.110.213.180",
    "Sport": 50102,
    "Dport": 80,
    "Source": [
      "192.168.20.7",
      50102
    ],
    "Destination": [
      "36.110.213.180",
      80
    ],
    "Time Start": 1658219896.623722,
    "Time End": 1658219896.665043,
    "Extensions": {
      "http.request.method": [
        [
          "GET",
          3
        ]
      ],
      "http.request.uri": [
        [
          "/huajiao_8.4.3.db",
          3
        ]
      ],
      "http.host": [
        [
          "sdk.live.360.cn",
          3
        ]
      ],
      "http.user_agent": [
        [
          "curl/7.29.0",
          3
        ]
      ],
      "http.request.line": [
        [
          "User-Agent: curl/7.29.0\\r\\n,Host: sdk.live.360.cn\\r\\n,Accept: */*\\r\\n",
          3
        ]
      ]
    }
  },
  {
    "flow_info": [
      "花椒直播ios1_1-10000.pcapng",
      "tcp",
      "3"
    ],
    "Src IP": "192.168.20.7",
    "Dst IP": "114.116.245.113",
    "Sport": 50825,
    "Dport": 443,
    "Source": [
      "192.168.20.7",
      50825
    ],
    "Destination": [
      "114.116.245.113",
      443
    ],
    "Time Start": 1658219895.80743,
    "Time End": 1658219895.969648,
    "Extensions": {
      "tls.handshake.extensions_server_name": [
        [
          "domain.huajiao.com",
          3
        ]
      ],
      "tls.handshake.certificate": [
        [
          "308206723082055aa0030201020211008011a2324fdfef2004f944785a28c858300d06092a864886f70d01010b0500305c310b300906035504061302434e311a3018060355040a1311576f54727573204341204c696d697465643131302f06035504030c28576f54727573204f562053657276657220434120205b52756e20627920746865204973737565725d301e170d3232303431393030303030305a170d3233303531393233353935395a3068310b300906035504061302434e3112301006035504080c09e58c97e4baace5b882312d302b060355040a0c24e58c97e4baace5af86e5a283e5928ce9a38ee7a791e68a80e69c89e99990e585ace58fb83116301406035504030c0d2a2e6875616a69616f2e636f6d30820122300d06092a864886f70d01010105000382010f003082010a0282010100c6d0fac599fd9f1f5373958607d5a62b84066168f1ccfcb91ccb65775f409b3625fa9609d7e6346e616427dc5576c8032e12ed8712205487bda6da2adb7738c886dbe82e945d314bb9db6eb3c70ab02a91c221cb79ea02aab11252e5f44a8801c431889fe0ebcc8c440fab5799b755883618c3c651cf45f3693a7443ac8a10ffa5bdc770a96468ae48ef0b3c2e54852f98e49666845b382c2d4559ffb56fd9a8aa19d3c0996d75dc0af4843e74236fd6bc7a1bc290c834336160bc09bffb5528deeab69a356a06abe110db1fd54c6a39379baf7ba3eaa0caaf3eed83aa5bcc8aeea6eb62ed898f93634f2c47a051e0d0b020accb5259e161c9496640a71a1d7d0203010001a38203213082031d301f0603551d230418301680140d498f15337bc04fb6fb3a3809fc3415da60dd14301d0603551d0e0416041486cbfcf763918a5c9b7d4add25ac44924d7f6f81300e0603551d0f0101ff0404030205a0300c0603551d130101ff04023000301d0603551d250416301406082b0601050507030106082b0601050507030230490603551d20044230403034060b2b06010401b231010202163025302306082b06010505070201161768747470733a2f2f7365637469676f2e636f6d2f4350533008060667810c010202303d0603551d1f043630343032a030a02e862c687474703a2f2f63726c2e63726c6f6373702e636e2f576f547275734f5653657276657243415f322e63726c306c06082b060105050701010460305e303806082b06010505073002862c687474703a2f2f6169612e63726c6f6373702e636e2f576f547275734f5653657276657243415f322e637274302206082b060105050730018616687474703a2f2f6f6373702e63726c6f6373702e636e3082017d060a2b06010401d6790204020482016d048201690167007600adf7befa7cff10c88b9d3d9c1e3e186ab467295dcfb10c24ca858634ebdc828a00000180402ccf5c000004030047304502202166fa52919d6365ed7fc07fbbcf2465c1f6e48328dc85218a284d0ee7a9ca4f022100d831aaa31e28550fe1319350c334827f113bec687537bb84f012f3fa39db7c780075007a328c54d8b72db620ea38e0521ee98416703213854d3bd22bc13a57a352eb5200000180402ccf6300000403004630440220341cbb12e7027ec07154b32b0fcac7284ac9e405331cb2af626ab3a5884395480220511a332a6d8d003f737fb1e4530db92d66eeedb2632e2bbf687b744fa422ee04007600e83ed0da3ef5063532e75728bc896bc903d3cbd1116beceb69e1777d6d06bd6e00000180402ccf3d000004030047304502206724088f06d22078f09c5beea215aedb65ba3480df855e030c1832d9a00c4af7022100f2899c830a66c671958a587f02c013df5e4cffe6c18ec09572de2c09a764bc7c30250603551d11041e301c820d2a2e6875616a69616f2e636f6d820b6875616a69616f2e636f6d300d06092a864886f70d01010b050003820101005f2401dbae2efbb75728403dcce6fe984f9bd6d5a1c5a1f7e2c40dbad2de87a9189d912b48ce3bc601e24d6492c69f9411eb0366ea0d56f8b61599e03cdd905f319f1e6c81f46e656761d21487586e08e8951d3697b862f3f1860da3b860379d76f8f2fb2e89d91e53f13d1824f281a57dd2a862fc95dc87d0d3e13c2b3ab7f68ed6ed265f6b9b82fb068bfc79a4ac204c65b04e3a5ded886e561fe0f08755b969d3e3c82977eed8fd77ef6219c80affeb1ed353fbe259e803e4ffc9c6a399ec126007b398af191931ec93d542d9e31ce87bb5d0c0c757b369c9084ba7326f90033d7aac1c801ed4a07f647911d3016974dd9de2912f4f3aa8dca11113988c76,308205e1308203c9a00302010202101d082954384cbf74af69b991169bf02d300d06092a864886f70d01010c0500308188310b3009060355040613025553311330110603550408130a4e6577204a6572736579311430120603550407130b4a65727365792043697479311e301c060355040a131554686520555345525452555354204e6574776f726b312e302c06035504031325555345525472757374205253412043657274696669636174696f6e20417574686f72697479301e170d3230303130383030303030305a170d3330303130373233353935395a305c310b300906035504061302434e311a3018060355040a1311576f54727573204341204c696d697465643131302f06035504030c28576f54727573204f562053657276657220434120205b52756e20627920746865204973737565725d30820122300d06092a864886f70d01010105000382010f003082010a0282010100804452eaea4a90459e1274530f75ddd725370e755553e5bbd9671d15543ae4c374e648096841515f461a833925e0e02b0869aeb8a854ab0b76b9b1cf0b811871ec051dbe851d7ef771218d6ea32c515a9a163bca135244a71178c43dffb3adc5397164ce8b7db158bf6f92561db3b88e43082c2801c3cede1a9fc30b1af70bc401dc8b288a7031211d93865073b96ca682abe90fdab2427d54a536f77297507cabe686597a22d205c654bed65f8a5c5a3f831ae2136cb076333332b6c7b83232c9f38cda5e1d140f84939720fcb6efdf6a477123043b2b7fe93f74681a3d51f42bcc597514f9f66628d2d6e79eb985df418775a4cfc6f802980c0fda374548d30203010001a38201703082016c301f0603551d230418301680145379bf5aaa2b4acf5480e1d89bc09df2b20366cb301d0603551d0e041604140d498f15337bc04fb6fb3a3809fc3415da60dd14300e0603551d0f0101ff04040302018630120603551d130101ff040830060101ff020100301d0603551d250416301406082b0601050507030106082b0601050507030230220603551d20041b3019300d060b2b06010401b231010202163008060667810c01020230500603551d1f044930473045a043a041863f687474703a2f2f63726c2e7573657274727573742e636f6d2f55534552547275737452534143657274696669636174696f6e417574686f726974792e63726c307106082b0601050507010104653063303a06082b06010505073002862e687474703a2f2f6372742e7573657274727573742e636f6d2f55534552547275737452534141414143412e637274302506082b060105050730018619687474703a2f2f6f6373702e7573657274727573742e636f6d300d06092a864886f70d01010c050003820201000e46ed703e7cd2b28fb172ba8b68208dfcff7d9e67852b0b5bc614f12d0f2774cb33abafb4af414a0ed862f1173210d12b2030d5c9e140213244c3cb3d4e034b71d20d068ce41704603fc9f451ed2822b5124075baa43dfa69327f9db4a5c21c7c77e688532f43e495175b99769cbd1eeb5d422224c76cbd966a63073e0e9189f99bf4b1125910bee99b5a19bfa115f94ce30253a72deeb2ae7c8373df4a9351ff4453d4cddb945a389547668c0d3d68322c18781d99abad126f6d358ea64f3508f913e4e40c3e413c555c90b7918b72f25c152e06f5cfb1d2ed04d96bf8b131b420ddeba9237947b6fd86d31c5e1a8b93d93eb690c606ce249c9c822cc697f24e82b2103d438b490bd7971a4a12a4bed33e8aa95e766dca363cdac2d1ff082cabb0d27b1f860706cb8e9d4aef1f994f7e153e9eeb58b69ed78abedf2a9244a4009290c5151661db8ddb8986fce38892878e3dd6078bea847dbc88ab18a2a9c1fd71980b2bd015b89a0ab6deef836d4ecab5a2ed2e53fd66d37d3cfd5cbed019ef19383659c7a779d2ea3f9433a65e6de9fe4746029bd417552b2fea20db68c12e2d0db3ac7309fceb2374a90bd69bbd4f04f449f140006ebbf80cfc1eb775b699cd2b0c545c5e1020fd9cc5afec81fefebab21a68ea109ce029d3c6bd786aa5e6d0d47856ad5fa3fa2a5c8e99570758f7182a330c5b278a75c6d74d8deb00bc,3082058130820469a00302010202103972443af922b751d7d36c10dd313595300d06092a864886f70d01010c0500307b310b3009060355040613024742311b301906035504080c1247726561746572204d616e636865737465723110300e06035504070c0753616c666f7264311a3018060355040a0c11436f6d6f646f204341204c696d697465643121301f06035504030c18414141204365727469666963617465205365727669636573301e170d3139303331323030303030305a170d3238313233313233353935395a308188310b3009060355040613025553311330110603550408130a4e6577204a6572736579311430120603550407130b4a65727365792043697479311e301c060355040a131554686520555345525452555354204e6574776f726b312e302c06035504031325555345525472757374205253412043657274696669636174696f6e20417574686f7269747930820222300d06092a864886f70d01010105000382020f003082020a028202010080126517360ec3db08b3d0ac570d76edcd27d34cad508361e2aa204d092d6409dcce899fcc3da9ecf6cfc1dcf1d3b1d67b3728112b47da39c6bc3a19b45fa6bd7d9da36342b676f2a93b2b91f8e26fd0ec162090093ee2e874c918b491d46264db7fa306f188186a90223cbcfe13f087147bf6e41f8ed4e451c61167460851cb8614543fbc33fe7e6c9cff169d18bd518e35a6a766c87267db2166b1d49b7803c0503ae8ccf0dcbc9e4cfeaf0596351f575ab7ffcef93db72cb6f654ddc8e7123a4dae4c8ab75c9ab4b7203dca7f2234ae7e3b68660144e7014e46539b3360f794be5337907343f332c353efdbaafe744e69c76b8c6093dec4c70cdfe132aecc933b517895678bee3d56fe0cd0690f1b0ff325266b336df76e47fa7343e57e0ea566b1297c3284635589c40dc19354301913acd37d37a7eb5d3a6c355cdb41d712daa9490bdfd8808a0993628eb566cf2588cd84b8b13fa4390fd9029eeb124c957cf36b05a95e1683ccb867e2e8139dcc5b82d34cb3ed5bffdee573ac233b2d00bf3555740949d849581a7f9236e651920ef3267d1c4d17bcc9ec4326d0bf415f40a94444f499e757879e501f5754a83efd74632fb1506509e658422e431a4cb4f0254759fa041e93d426464a5081b2debe78b7fc6715e1c957841e0f63d6e962bad65f552eea5cc62808042539b80e2ba9f24c971c073f0d52f5edef2f820f0203010001a381f23081ef301f0603551d23041830168014a0110a233e96f107ece2af29ef82a57fd030a4b4301d0603551d0e041604145379bf5aaa2b4acf5480e1d89bc09df2b20366cb300e0603551d0f0101ff040403020186300f0603551d130101ff040530030101ff30110603551d20040a300830060604551d200030430603551d1f043c303a3038a036a0348632687474703a2f2f63726c2e636f6d6f646f63612e636f6d2f414141436572746966696361746553657276696365732e63726c303406082b0601050507010104283026302406082b060105050730018618687474703a2f2f6f6373702e636f6d6f646f63612e636f6d300d06092a864886f70d01010c05000382010100188751dc74213d9c8ae027b733d02eccecf0e6cb5e11de226f9b758e9e72fee4d6feaa1f9c962def034a7eaef48d6f723c433bc03febb8df5caaa9c6aef2fcd8eea37b43f686367c14e0cdf4f73ffedeb8b48af09196fefd43647efdccd201a17d7df81919c9422b13bf588bbaa4a266047688914e0c8914cea24dc932b3bae8141abc71f15bf0410b98000a220310e50cb1f9cd923719ed3bf1e43ab6f945132675afbbaaef3f7b773bd2c402913d1900d3175c39db3f7b180d45cd9385962f5ddf59164f3f51bdd545183fed4a8ee80661742316b50d50732744477f105d892a6b853114c4e8a96a4c80bc6a78cfb87f8e7672990c9dfed7910816a1a35f95",
          8
        ]
      ]
    }
  },
 ···
```
